//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop4DVDS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OrderDetail
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> Total { get; set; }
        public string PayMethod { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public string ProductName { get; set; }
        public string Contact { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual tbl_Invoice tbl_Invoice { get; set; }
        public virtual tbl_Product tbl_Product { get; set; }
    }
}
